#!/usr/bin/python
# -*- coding: utf8 -*-

mydict = {
'ヤングチャンピオン':'Young Champion',
'ヤングアニマル嵐':'Young Animal Arashi',
'ヤングガンガン':'Young GANGAN',
'ヤングアニマル':'Young Animal',
'プレイボーイ':'Weekly Playboy WPB',
'ビッグコミックスピリッツ':'Spi-net.jp',
'ヤングジャンプ':'Young Jump',
'ビッグコミックスピリッツ':'Big Comic Spirits',
'プレイボーイ':'Weekly Playboy WPB',
'ヤングジャンプ':'Young Jump',
'PB写真集':'PBJ',
'ROSI写真':'ROSI',
'2011年':'2011-',
'月號':'',
'月刊':'',
'少年サンデー':'Sunday',
'合集':'',
#top 20
"高橋愛":"Ai Takahashi",
"麻倉憂":"Yu Asakura",
"黒田有彩":"Arisa Kuroda",
"ヤングマガジン":"Young Magazine",
"ヤングチャンピオン":"Young Champion",
"初写美人":"Bejean Online",
"吉沢明歩":"Akiho Yoshizawa",
"夏菜":"Natsuna",
"宮澤佐江":"Miyasa Ayasae",
"小池唯":"Yui Koike",
"梅宮万紗子":"Masako Umemiya",
"武井咲":"Emi Takei",
"瀬戸早妃":"Saki Seto",
"篠田麻里子":"Mariko Shinoda",
"足立梨花":"Rika Adachi",
"鈴木ふみ奈":"Fumina Suzuki",
"鈴木愛理":"Airi Suzuki",
"フライデー":"Friday",
"アイドリング!!!":"Idoling!!!",
"京本有加":"Yuka Kyomoto",
"北原里英":"Rie Kitahara",
"峯岸みなみ":"Minami Minegishi",
"月刊エンタメ":"EN TAME",
"松井玲奈":"Rena Matsui",
"ヤングガンガン":"Young GANGAN",
"中村静香":"Shizuka Nakamura",
"制服美少女天國":"DGC",
"小松彩夏":"Ayaka Komatsu",
"ヤングアニマル嵐":"Young Animal Arashi",
"次原かな":"",
"渡辺麻友":"Mayu Watanabe",
"甲斐まり恵":"Marie Kie",
"前田敦子":"Atsuko Maeda",
"森田涼花":"Morita Suzuka",
"池田夏希":"Natsuki Ikeda",
"熊田曜子":"Yoko Kumada",
"西田麻衣":"Mai Nishida",
"小嶋陽菜":"Haruna Kojima",
"山本梓":"Asuza Yamamoto",
"川村ゆきえ":"Yukie Kawamura",
"现役女子高生":"Minasuki.tv",
"磯山さやか":"Sayaka Isoyama",
"私立Bejean女学館":"Bejean Online",
"逢沢りな":"Rina Aizawa",
"大島優子":"Yuko Oshima",
"ヤングアニマル":"Young Animal",
"杉原杏璃":"Anri Sugihara",
"柏木由紀":"Yuki Kashiwagi",
"篠崎愛":"Ai Shinozaki",
"原幹恵":"Mikie Hara",
"ヤングジャンプ":"Young Jump",
"プレイボーイ":"Weekly Playboy",
"他":"Him",
"佐山彩香":"Ayaka Sayama",
"ビッグコミックスピリッツ":"Big Comic Spirits",
"匿名写真":"ROSI.CC",
"吉木りさ":"Risa Yoshiki"
}
